### ISSUE TITLE
Support for tinymist

### ISSUE THREAD

**Issue by felipeacsi** [havarddj/typst-preview.el#5]
Hello,

since [typst-preview](https://github.com/Enter-tainer/typst-preview) was deprecated in favour of [tinymist](https://github.com/Myriad-Dreamin/tinymist), is there a way to give support for it?

I don't know any internals, but it seems that the develolper of `typst-preview` added that code to `tinymist`. From an user standpoint, one can use `tinymist preview` instead of `typst-preview` after installing `tinymist`.

I've looked through the code, but honestly is too much elisp for me, but I would be happy if I can help with anything.

Do you think is it possible to support `tinymist`?

Thanks in advance,

Felipe

**Comment by havarddj** [comment]
Hi Felipe! Thanks for reminding me about this. The change from typst-preview to tinymist came at a busy time for me, so I forgot to update. It should work now.  I've also added some functionality to stop the annoying master prompts in a similar way to how auctex does it, please let me know how it works and if you have any other troubles, concerns or requests.

**Comment by felipeacsi** [comment]
That was really fast!

Unfortunately it doesn't work on my machine. I have the same error: `Searching for program: Not found: typst-preview`.

Even I've changed my configuration file with: `(setq typst-preview-executable "tinymist preview")`. But nothing happened.

I'm using doom and I rebuilt everything and still the same error.

Do you have any clue?

**Comment by havarddj** [comment]
Oopsie, my bad. I used  `eq` instead of `string=` to compare strings and stupidly didn't test. Try now maybe?

**Comment by felipeacsi** [comment]
Now it works! Thank you!

**Comment by havarddj** [comment]
No problem, glad it works!
